---
title: "documents"
author: "aleksada"
date: "May 16, 2015"
output: html_document
runtime: shiny
---

# Application
This is an application to verify the law of large number and central limit theorem for binomial distribution. It may need a little bit knowledge of probability. More background can be found in wikipedia.

[Central Limit Theorem](http://en.wikipedia.org/wiki/Central_limit_theorem)

[Law of Large Number](http://en.wikipedia.org/wiki/Law_of_large_numbers)

Basically, the ideal results is that, when the sample size is large, the sample mean and variance will be close to true mean of given distribution, and the histogram of the distribution will close to normal distribution.

# Inputs and Outputs

1.Inputs

Sample Size: It is the number of observations for given distribution. (From 10 to 10000)

The binomial distribution with parameters n and p is the discrete probability distribution of the number of successes in a sequence of n independent yes/no experiments, each of which yields success with probability p.

Probability of Success: p (From 0.1 to 0.9).

Number of Trials: n (From 100 to 1000).

2.Outputs

We want to see that when sample size is large, the sample mean and variance will be close to the true mean and variance(mean=np,var=np(1-p)), and it is the weak law of large number.
And we want to see that, when the number of trials increase, the binomial distribution will be approximately normalized. But this result also need enough sample size.

